### ISSUE TITLE
Compatibility With Bewitchment 

### ISSUE THREAD

**Issue by ArcusMG** [williambl/haema#100]
I don’t seem to be able to launch Minecraft with the latest version of Bewitchment (and it’s dependencies) and Haema installed.

Minecraft version 1.17.1
Fabric loader 0.12.8
trinkets-3.0.4
bewitchment-1.17-16
cloth-config-5.1.40-fabric
fabric-api-0.44.0+1.17
fabric-language-kotlin-1.7.0+kotlin.1.6.0
haema-1.7.7+1.17
impersonate-2.3.5, pal-1.4.0
Patchouli-1.17.1-59-FABRIC
Pehkui-3.0.0+1.14.4-1.18

This is the crash log I get: [crash-2021-12-07_18.14.49-client.txt](https://github.com/williambl/haema/files/7672852/crash-2021-12-07_18.14.49-client.txt)

**Comment by williambl** [comment]
Try Haema 1.7.8+1.17?

**Comment by ArcusMG** [comment]
> Try Haema 1.7.8+1.17?

That totally fixed it! I installed the mods via ATLauncher and that version wasn’t showing up but I found it on curse forge. Sweet!

**Comment by williambl** [comment]
That's because I only uploaded it five minutes ago :P glad it worked!
