### ISSUE TITLE
Minecraft Crashed 'cause failed injection check

### ISSUE THREAD

**Issue by twinkle365twink** [williambl/haema#101]
**Mod version:** _1.8.0_,
**Minecraft version:** _1.18.1_,
**Fabric version:** _0.12.12_,
**Fabric API version:** _0.45.0_.
 
**Issue:** 
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector showVampireBloodIcons(Lnet/minecraft/class_329;Lnet/minecraft/class_4587;IIIIII)V in haema.mixins.json:InGameHudMixin from mod haema failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap haema-refmap.json

**Crash report:**
[crash-2021-12-24_14.14.52-client.txt](https://github.com/williambl/haema/files/7774106/crash-2021-12-24_14.14.52-client.txt)

**Comment by williambl** [comment]
https://github.com/juancarloscp52/BedrockIfy/issues/27#issuecomment-729162464

**Comment by twinkle365twink** [comment]
Thanks!
