### ISSUE TITLE
Simply make blood injectors stackable

### ISSUE THREAD

**Issue by NyanMaths** [williambl/haema#115]
All is in the title, except you could let it configurable if applicable. Thank you by advance !

**Comment by williambl** [comment]
Not planned, sorry.

This would mess with the balance, making combat as a vampire far easier - without the challenge of inventory management, one could spam-right click on a blood injector stack to gain massive amounts of blood.

Making it configurable is unlikely to be simple, as item max stack counts are set before configuration is loaded (as Haema does all non-client configuration through gamerules).

Also, Blood Injectors will in future have NBT, allowing them to hold different blood types (#16) - Minecraft does not tend to like stacking of items with NBT, and it can get confusing.
