### ISSUE TITLE
Blackstone Altar Issue

### ISSUE THREAD

**Issue by KiwiParis** [williambl/haema#118]
Hello!

I'm using the origin mod as well as the bewitchment and have found that when I turned into a vampire via bewitchment (I didn't select vampire as my origin), that after using the blackstone altar once and relogging back in, I am unable to use it again? I'm not sure what the bug is. I add the correct items of the rituals I haven't preformed, stand on the altar and right click, nothing happens. The only thing I'm able to preform is the customize abilities ritual. When I attempt to use the other rituals, the water has particles, the candles send particles towards the middle, but still nothing, so I'm somewhat at my wits end. I have no idea why it refuses to give me the skill point and take the items (I haven't preformed all of the blackstone ritual altars, only 2. As I have 4 available skillpoints to move around). 

I'm unsure if this has been patched in an updated version, but I'm currently using haema 1.8.2+1.18.1

This is the altar I'm using:
![2022-03-21_17 10 13](https://user-images.githubusercontent.com/54605008/159204359-797b6273-b7b7-4072-a131-2544b1a2b647.png)

**Comment by williambl** [comment]
Hi! I don't think the candles you're using count for the blackstone altar; only soul torches and soul campfires can be used. Due to this, your altar is acting at the basic level instead (as can be seen by the regular flames floating inwards instead of soul flames).

**Comment by KiwiParis** [comment]
Thank you for your fast reply!

Yes, that seemed to be my issue, apologies!

**Comment by williambl** [comment]
All good :)
