### ISSUE TITLE
Game crashed when killed by vampire hunter

### ISSUE THREAD

**Issue by PixelatedBruh** [williambl/haema#12]
Time: 8/5/20 5:41 PM
Description: Ticking entity

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method com.williambl.haema.damagesource.DamageSourceExtensionsKt.isEffectiveAgainstVampires, parameter $this$isEffectiveAgainstVampires
	at com.williambl.haema.damagesource.DamageSourceExtensionsKt.isEffectiveAgainstVampires(DamageSourceExtensionsKt.java)
	at net.minecraft.class_1309.redirect$cak000$isActuallyDead(class_1309.java:17548)
	at net.minecraft.class_1309.method_5643(class_1309.java:1098)
	at net.minecraft.class_1657.redirect$cam000$damage(class_1657.java:13360)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:618)
	at net.minecraft.class_1308.method_6121(class_1308.java:1451)
	at net.minecraft.class_1366.method_6288(class_1366.java:142)
	at net.minecraft.class_1366.method_6268(class_1366.java:134)
	at com.williambl.haema.entity.VampireHunterMeleeAttackGoal.method_6268(VampireHunterMeleeAttackGoal.java:221)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:649)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:732)
	at net.minecraft.class_1309.method_6007(class_1309.java:2505)
	at net.minecraft.class_1308.method_6007(class_1308.java:538)
	at net.minecraft.class_1588.method_6007(class_1588.java:42)
	at net.minecraft.class_1309.method_5773(class_1309.java:2251)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$7504/1232456709.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$6491/1197479822.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.williambl.haema.damagesource.DamageSourceExtensionsKt.isEffectiveAgainstVampires(DamageSourceExtensionsKt.java)
	at net.minecraft.class_1309.redirect$cak000$isActuallyDead(class_1309.java:17548)
	at net.minecraft.class_1309.method_5643(class_1309.java:1098)
	at net.minecraft.class_1657.redirect$cam000$damage(class_1657.java:13360)
	at net.minecraft.class_1657.method_5643(class_1657.java:914)
	at net.minecraft.class_3222.method_5643(class_3222.java:618)
	at net.minecraft.class_1308.method_6121(class_1308.java:1451)
	at net.minecraft.class_1366.method_6288(class_1366.java:142)
	at net.minecraft.class_1366.method_6268(class_1366.java:134)
	at com.williambl.haema.entity.VampireHunterMeleeAttackGoal.method_6268(VampireHunterMeleeAttackGoal.java:221)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:649)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:732)
	at net.minecraft.class_1309.method_6007(class_1309.java:2505)
	at net.minecraft.class_1308.method_6007(class_1308.java:538)
	at net.minecraft.class_1588.method_6007(class_1588.java:42)
	at net.minecraft.class_1309.method_5773(class_1309.java:2251)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_3218.method_18762(class_3218.java:615)
	at net.minecraft.class_3218$$Lambda$7504/1232456709.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: haema:vampire_hunter (com.williambl.haema.entity.VampireHunterEntity)
	Entity ID: 1321
	Entity Name: Vampire Hunter
	Entity's Exact location: 339.96, 4.00, 193.98
	Entity's Block location: World: (339,4,193), Chunk: (at 3,0,1 in 21,12; contains blocks 336,0,192 to 351,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.09, -0.08, -0.10
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:603)
	at net.minecraft.class_3218.method_18765(class_3218.java:405)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Fort_Chungus'/109, l='ServerLevel[New World]', x=339.45, y=4.00, z=192.91]]
	Chunk stats: ServerChunkCache: 2736
	Level dimension: minecraft:overworld
	Level spawn location: World: (240,4,192), Chunk: (at 0,0,0 in 15,12; contains blocks 240,0,192 to 255,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11539 game time, 7689 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 163597 (now: false), thunder time: 112345 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at net.minecraft.server.MinecraftServer$$Lambda$6491/1197479822.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1438697232 bytes (1372 MB) / 5301075968 bytes (5055 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G
	Fabric Mods: 
		adabraniummod: Adabranium Mod 1.1.5.1
		adorn: Adorn 1.10.0+1.16.1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		antiqueatlas: Antique Atlas 5.3.0-fabric
		anvil_fix: AnvilFix 1.1.3+build.7-1.16
		artifice: Artifice 0.8.1+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		backrooms: The Backrooms 1.2.1
		battletowers: Battle Towers 3.0.2-beta-1.16.1
		bedrockwaters: BedrockWaters 1.3.0+1.16.1
		bettergraves: Better Graves 0.3.0
		betternether: Better Nether 3.5.4
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson 1.2.0
		blur: Blur 1.0.6
		bookworm: Bookworm Library 3.0.1
		bucket-hat: Bucket Hat 1.0.2
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		cakechomps: Cake Chomps FABRIC-1.16.1-1.0
		cardinal-components: Cardinal Components API 2.4.2
		cardinal-components-base: Cardinal Components API (base) 2.4.2
		cardinal-components-block: Cardinal Components API (blocks) 2.4.2
		cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.2
		cardinal-components-item: Cardinal Components API (items) 2.4.2
		cardinal-components-level: Cardinal Components API (world saves) 2.4.2
		cardinal-components-util: Cardinal Components API (utilities) 2.4.2
		cardinal-components-world: Cardinal Components API (worlds) 2.4.2
		cavebiomes: Cave Biomes 0.2.4
		chainmail: Chainmail 0.3.0
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.4.44
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		cotton: Cotton 1.0.5
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.5
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		craftpresence: CraftPresence 1.6.8
		creativebuttonmover: Creative Button Mover 0.2.5
		curios: Curios API 1.16.1-0.5
		curses: Curses 1.3.1
		dark-loading-screen: Dark Loading Screen 1.4.1
		darkness: True Darkness 1.5.43
		debrand: Debrand 1.0.2
		ducts: Ducts 1.0.1
		earthtojavamobs: Earth2Java 1.1.0+1.16.1
		easierenchanting: Easier Enchanting 1.2.0
		emotecraft: Emotecraft 0.11.4
		enchantablehorsearmor: Enchantable Horse Armor 1.0a
		enderitemod: Enderite Mod 1.1.1
		endreborn: End: Rebellion 1.6
		expandedstorage: ExpandedStorage 5.3.16
		extraorigins: Extra Origins r9
		extrapieces: Extra Pieces 2.9.0
		fabric: Fabric API 0.16.0+build.384-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+013e49d202
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-2
		flonters: Flonters 1.1.0+1.16.1
		flowing_background: Flowing Background 1.2.0+1.16.1
		fluidphysics: Fluid Physics 1.2.3+1.16.1
		gbfabrictools: GBfabrictools 1.2.2+1.16
		givemehats: Give Me Hats! 1.2.8
		grindenchantments: Grind Enchantments 1.1.1+1.16.1
		gubbins: Gubbins 1.1.1-1.16.1
		haema: Haema 1.2.0
		healthoverlay: Health Overlay 3.6.12
		hookshot: Hookshot 9.0
		houraielixir: Hourai Elixir r3
		howlingwolves: Howling Wolves 1.0.0+build.1
		illuminations: Illuminations 1.0.3
		images: Images 0.1.0
		inmis: Inmis 1.2.0-1.16.1
		jankson: Jankson 3.0.0+j1.2.0
		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
		kittycamp: Kitty Camp 1.0.0
		koi: Koi Fish 1.0.2
		lakeside: Lakeside 1.0.2+1.16.1
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.2.0+1.16.1
		library_of_exile: Library of Exile 1.0.0
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		magna: Magna 1.2.0-1.16.1
		mighty_mangoes: Mighty Mangoes 1.0.0
		minecraft: Minecraft 1.16.1
		mm: Manningham Mills 2.0.1
		mmorpg: Age of Exile 1.0.7
		mo_glass: Mo Glass 1.3-MC1.16.1
		modmenu: Mod Menu 1.12.2+build.17
		moenchantments: Mo'Enchantments 1.12.4-beta2
		mooblooms: Mooblooms 1.3.1
		more_gems: More Gems 1.0.46
		moreberries: More Berries 1.3.1
		morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.0
		moretotems: More Totems 2.5
		netheritehorsearmor: Netherite Horse Armor 0.4.0+1.16.1
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		nomadbooks: Nomad Books 0.5.4
		noplayerlabels: No Player Labels 1.0.1
		now-playing: Now Playing 1.1.3
		org_aeonbits_owner_owner: owner 1.0.12
		org_javassist_javassist: javassist 3.26.0-GA
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		org_reflections_reflections: reflections 0.9.12
		origins: Origins 1.16-0.2.7
		overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
		p3utils: P3NG00's Utilities 0.0.0
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-38-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		pigpoop: Pig Poop 1.1.3
		portaltags: Portal Tags 1.0.0+1.16.1
		presencefootsteps: Presence Footsteps r26+1.16-rc1
		pumice: Pumice 0.0.1
		rare-ice: Rare Ice 0.2.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reliccraft: RelicCraft 1.0.28+1.16.1
		repurposed_structures: Repurposed Structures 1.4.0
		ringsofascension: Rings of Ascension 1.0.5
		rotten: FleshZ 1.2.2
		roughlyenoughitems: Roughly Enough Items 4.10.5
		sandwichable: Sandwichable 1.1.1-snapshot
		satin: Satin 1.4.0-nightly.1.16-pre5+build.1
		shapes: Shapes 2.0.0+build.10
		sheepconsistency: Sheep Consistency 1.0.2
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		simplyplatinum: Simply Platinum 2.0.0
		sizeentityattributes: Size Entity Attributes r2
		sodium: Sodium 0.1.0
		spinnery: Spinnery 3.0.48
		spruceui: SpruceUI 1.5.8
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		structure-helpers: Structure Helpers 2.1.0
		stuffz: StuffZ 2.2.2
		talltallcane: Tall Tall Cane 1.0
		terraform: Terraform 2.1.7+build.31
		terrestria: Terrestria 2.0.4+build.50
		traverse: Traverse 2.2.14+build.28
		trinkets: Trinkets 2.6.2
		trumpet-skeleton: Trumpet Skeleton 1.1.2
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanilla-hammers: Vanilla Hammers 2.0.3-1.16.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		walljump: Wall-Jump! 1.3.3+1.16.1
		water-erosion: Water Erosion 1.1.1
		wendigoism: Wendigoism r7
		wildworld: Wild World 1.2.3-1.16
		window_title_changer: Window Title Changer 2.0.0-1.16.1
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		woodcutter: Woodcutter 1.2-1.16.1
		worldedit: WorldEdit 7.2.0-beta-01+0eb9ac7
		worldtime: WorldTime 1.16-fabric0.13.1-1.2.1
	Patchouli open book context: n/a
	Player Count: 1 / 8; [class_3222['Fort_Chungus'/109, l='ServerLevel[New World]', x=339.45, y=4.00, z=192.91]]
	Data Packs: vanilla, fabric/betternether, fabric/mo_glass, fabric/moretotems, fabric/morecraftingtables, fabric/bunch-o-trinkets, fabric/rotten, fabric/repurposed_structures, fabric/ducts, fabric/hookshot, fabric/battletowers, fabric/enderitemod, fabric/structure-helpers, fabric/curios, fabric/origins, fabric/gubbins, fabric/adorn, fabric/woodcutter, fabric/terrestria, fabric/vanillaexcavators, fabric/mmorpg (incompatible), fabric/netheritehorsearmor, fabric/wolveswitharmor, fabric/antiqueatlas, fabric/cotton-commons, fabric/mooblooms, fabric/inmis, fabric/backrooms, fabric/cinderscapes, fabric/images, fabric/lambdynlights, fabric/adabraniummod, fabric/wendigoism, fabric/pumice, fabric/fabric-tool-attribute-api-v1, fabric/extraorigins, fabric/rare-ice, fabric/blockus, fabric/endreborn, fabric/expandedstorage, fabric/earthtojavamobs, fabric/koi, fabric/libcd, fabric/vanilla-hammers, fabric/nomadbooks, fabric/flonters, fabric/sandwichable, fabric/traverse, fabric/wildworld, fabric/more_gems, fabric/moreberries, fabric/trumpet-skeleton (incompatible), fabric/stuffz, fabric/simplyplatinum, fabric/fabric-furnaces, fabric/mighty_mangoes, extrapieces:ep_data, fabric/haema, fabric/kittycamp, fabric/reliccraft
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by williambl** [comment]
Fixed in v1.2.1. Thanks for your report.
