### ISSUE TITLE
Lunadedogs Canera

### ISSUE THREAD

**Issue by Thingw31** [williambl/haema#127]
Based on the small amount i know of Crash logs, I think (not know) that this is because the camera has a issue being related to haema but im not sure which mods is at fault....

[crash-2022-05-14_05.14.29-client.txt](https://github.com/williambl/haema/files/8692793/crash-2022-05-14_05.14.29-client.txt)

**Comment by williambl** [comment]
I believe this bug is fixed in 1.9.7 for Minecraft 1.18.2. Unfortunately I don't have the time to backport fixes to old Minecraft versions.
