### ISSUE TITLE
Shields deflecting arrows cause damage to vampiric health.

### ISSUE THREAD

**Issue by Bombbery** [williambl/haema#13]
Shields deflecting projectiles, under normal circumstances, does not cause damage to the player (usually). 

*However*, when playing as a vampire - and you have extra health - an interesting effect occurs. If you deflect an arrow and walk in the direction it was fired shortly after the deflection, you *still* take damage on both your blood thirst meter and extra health. This effect disappears when all the extra HP is gone. 

Video linked showing the bug:
https://youtu.be/jyODmM-aASU

**Comment by williambl** [comment]
Note to self: inject before `this.limbDistance = 1.5F;` in `LivingEntity#damage`
