### ISSUE TITLE
Vampiric Zombies

### ISSUE THREAD

**Issue by ImagineWagons115** [williambl/haema#132]
When drinking from zombies they become vampiric zombies which pretty much nullifies them as a source of blood which was helpful during combat. If this is the actual plan for them and not an oversight, then the random zombies I turn into vampiric zombies should identify me as their "owner" like with the Vampirager becoming my allies instead of attacking me and slowly withering away

**Comment by williambl** [comment]
Removed players being able to make vampiric zombies in 1.10.3+1.19. I'll backport this to 1.18.2 at some point.
