### ISSUE TITLE
Cursemaven not able to get Rat's Mischief from Curseforge

### ISSUE THREAD

**Issue by Luansr01** [williambl/haema#134]
When trying to download Rat's Mischief with Cursemaven, the server delivers an "error 403: forbidden".
The same happens when using the Cursemaven test url with Rat's Mischief's info, so maybe it's an issue with the maven itself?
Nevertheless, I'm unable to build the mod with this dependency.

**Comment by williambl** [comment]
Thanks for reporting - for now I have published Rat's Mischief onto my maven to get around this. See 4f02668.

**Comment by williambl** [comment]
It's now published on the ladysnake maven too, so I'm closing this.
