### ISSUE TITLE
Crash with error code 255 in fabric

### ISSUE THREAD

**Issue by kazmath** [williambl/haema#144]
Crash report.
[crash-2022-11-27_20.14.37-client.txt](https://github.com/williambl/haema/files/10099421/crash-2022-11-27_20.14.37-client.txt)

I don't really have much additional information, I only have haema and its libs loaded in fabric, everything at the latest stable version as of now (Fabric loader is 0.14.10, but that should be in the crash report).
```
~/.minecraft/mods/
  fabric-api-0.67.1+1.19.2.jar
  fabric-language-kotlin-1.8.6+kotlin.1.7.21.jar
  geckolib-fabric-22w45a-3.1.37.jar
  haema-1.10.4+1.19.jar
```
Fabric's crash window opened when I tried loading haema alone, but when I loaded all dependencies it didn't even open and just straight up crashed

I'm in arcolinux using minecraft's official launcher (also tried multimc) in xfce if that matters.

**Comment by williambl** [comment]
Hi, you're using Geckolib for 22w45a, not for 1.19.2.
