### ISSUE TITLE
Unable to start mod, missing requirement that cannot be found.

### ISSUE THREAD

**Issue by Vozziie** [williambl/haema#146]
When starting the game, using Fabric, an error page says haema (1.10.4 + 1.19) cannot run without "geckolib3" I have downloaded the fabric and eventually forge version of geckolib but it continues to say I am missing the requirement.
The current version is Fabric Loader 0.14.12 or Fabric API 1.19.3

I am unsure how to fix this issue, any assistance would be greatly appreciated.

**Comment by williambl** [comment]
haema is only for 1.19.2, make sure you're using 1.19.2 and running a version of geckolib for 1.19.2 not 1.19.3.

**Comment by Vozziie** [comment]
I see, sorry for the inconvenience and thank you for your time.
