### ISSUE TITLE
Mod conflict with BedrockIfy

### ISSUE THREAD

**Issue by RDKRACZ** [williambl/haema#19]
MC crashes when loading Haema and BedrockIfy mod.

Reported to juancarloscp52 too - https://github.com/juancarloscp52/BedrockIfy/issues/27

crash report - https://hatebin.com/tbgimqyrle
latest.log - https://hatebin.com/ithepnggws

**Comment by williambl** [comment]
Fixed by Bedrockify. Thanks @juancarloscp52 !
