### ISSUE TITLE
Shader incompatibility with Crimson Moon

### ISSUE THREAD

**Issue by kotx** [williambl/haema#20]
Seems like the grayscale vampire shader is incompatible with [Crimson Moon's shader](https://github.com/Draylar/crimson-moon/blob/1.16.2/src/main/resources/assets/crimsonmoon/shaders/post/crimson.json). The screen is just black.

**Comment by williambl** [comment]
Thanks for reporting this. Does it still happen if you use this build? (This dev build has a different shader, which may or may not have an effect on the bug)

[testbuild.zip](https://github.com/williambl/haema/files/5759161/testbuild.zip)

**Comment by kotx** [comment]
> 
> 
> Thanks for reporting this. Does it still happen if you use this build? (This dev build has a different shader, which may or may not have an effect on the bug)
> 
> [testbuild.zip](https://github.com/williambl/haema/files/5759161/testbuild.zip)

Unfortunately there's no change. Screen turns black on Crimson Moons. ![screenshot](https://uwu.foundation/6Su8fZ5.png)

**Comment by williambl** [comment]
Hi, please try [this build](https://cdn.discordapp.com/attachments/650824359547764746/797583346020384804/haema-1.4.0.jar)? :)

**Comment by kotx** [comment]
> 
> 
> Hi, please try [this build](https://cdn.discordapp.com/attachments/650824359547764746/797583346020384804/haema-1.4.0.jar)? :)

Still no luck. It's possible this can only be fixed on Crimson Moon's side?

**Comment by williambl** [comment]
> Still no luck. Is it possible this can only be fixed on Crimson Moon's side?

I tried applying the change to crimson moon too and it still didn't work. Hypothesis is, it's a Satin API bug. [An issue has been opened](https://github.com/Ladysnake/Satin/issues/13)

**Comment by williambl** [comment]
Potentially fixed in latest Satin.

**Comment by itsNordLord** [comment]
Doesnt seem like an issue with Haema. Night Vision itself is causing the same blackscreen without Haema even installed. 
![image](https://user-images.githubusercontent.com/68762570/117344152-f32bfa00-ae59-11eb-9b6f-a2c5f1572add.png)

**Comment by williambl** [comment]
It was an issue with Satin when multiple shaders were run. Thought to be fixed now.
