### ISSUE TITLE
Make the generation of vampire blood configurable/disableable

### ISSUE THREAD

**Issue by jdnoble3** [williambl/haema#27]
If using the Origins mod, I could see it being disabled in generation. Or just in general, possibly for a modpack with a specific scene

**Comment by williambl** [comment]
Thanks for the suggestion. I'll make it configurable by changing a loot table in a datapack.

**Comment by keinkaihere** [comment]
bump

**Comment by williambl** [comment]
Can be modified in 1.8 by changing `haema:injected/chests/dungeon_blood` and `haema:injected/chests/temple_blood` loot tables.
