### ISSUE TITLE
Deconversion command not working

### ISSUE THREAD

**Issue by Tankuu** [williambl/haema#29]
Upon writing:
`/haema deconvert [name]`

I am given an error in chat stating:
`Unknown or incomplete command, see below for error`
In which the error points towards my player name.

**Comment by williambl** [comment]
Oh, I misplaced a single bracket in my code, whoops. Thanks for the report :)

**Comment by Tankuu** [comment]
> Oh, I misplaced a single bracket in my code, whoops. Thanks for the report :)

No problem! It was very troubling as I didn't want to have to create a new world when I didn't want to be a vampire anymore, as I wasn't sure how to deconvert without the command.

**Comment by williambl** [comment]
Fixed in 1.5.2.

**Comment by Tankuu** [comment]
> Fixed in 1.5.2.

Er- are you sure?
I enter the command and now just nothing happens.

**Comment by williambl** [comment]
If you became a vampire through Origins, you can only deconvert through Origins, too
