### ISSUE TITLE
Constant damage ticking

### ISSUE THREAD

**Issue by Tankuu** [williambl/haema#30]
I believe that this happened upon using the empty injector whilst I was in creative mode, and effectively empty on blood. I used it, nothing happened, however upon switching to survival I had no health and no blood.

### Side-effects:
- My screen is indefinitely tilted/tilting as if I am being hit indefinitely
- My health is always not filled, however when I am damaged, I lose no hearts and am thus invincible (tested with a smite enchanted wooden sword)
- The level of my blood doesn't fix it
- I seem to be entirely unable to collect XP
- Unable to collect/consume blood?

### How to reproduce:
**Method 1:**
- Extract all of your blood whilst in creative mode

**Method 2:**
- Extract all of your blood whilst in survival mode
- Let yourself get damaged until empty hearts

### Image:
![image](https://user-images.githubusercontent.com/63684195/107887696-f99f7b00-6ed5-11eb-9e7b-bbe8f99e3d20.png)

### Conclusion:
I am not entirely sure of the nature of this bug or how to re-produce it, but I will be trying different methods to see what I can do to fix it as well as re-produce it.

The big problem with this bug is that if you will effectively lose your world unless you are technological enough to edit the player files and remove your vampire presence.

There was nothing in my `latest.log` that would have helped.

**Comment by williambl** [comment]
ooooofff, looks like the return of a very old bug from last year. I'll look into it, thanks.

**Comment by Tankuu** [comment]
> ooooofff, looks like the return of a very old bug from last year. I'll look into it, thanks.

I haven't looked into the code whatsoever, although my most logical assumption is that it has to do with something related to a damage source being confused and just looping, as it continues to detect its cause, play its effect, detect its cause...

Not quite sure though. I haven't looked into it with what's public.

**Comment by williambl** [comment]
@Tankuu does the issue persist with this dev build?
[devbuild.zip](https://github.com/williambl/haema/files/6038436/devbuild.zip)

**Comment by williambl** [comment]
Should be fixed in 1.6.
