### ISSUE TITLE
Allow Origins to deconvert you after you change your origin (with Orb of Origin)

### ISSUE THREAD

**Issue by Tankuu** [williambl/haema#34]
Just a general suggestion.

Otherwise, you are technically two origins at once.

**Comment by williambl** [comment]
This should be working in 0.5.2. You need to die after chamging origins for your hunger to go back to normal though.

**Comment by Tankuu** [comment]
> This should be working in 0.5.2. You need to die after chamging origins for your hunger to go back to normal though.

I'll test it again and see if I can get it. I just know that when I change, the shaders and everything stayed the exact same. I'll test it again and let you know!

**Comment by Tankuu** [comment]
**Update:** Not sure if I'm doing anything wrong, but here is what I did:
- Used Orb of Origin to change to vampire
- Used Orb of Origin to change to human
- Typed /kill

I then respawned in the same spot as if I never died and still have each of the effects of the vampire.
My recommendation is to make it so the void can kill the vampire, as that is what I believe the `kill` command does.

**Comment by williambl** [comment]
`DamageSource.OUT_OF_WORLD` (which is used by void and by `/kill`) is a vampire-effective source, though :/ Odd that it's not working.

**Comment by Tankuu** [comment]
> `DamageSource.OUT_OF_WORLD` (which is used by void and by `/kill`) is a vampire-effective source, though :/ Odd that it's not working.

I could make that into a separate issue if you would like, assumingly being a bug. I haven't tested it with jumping into the void, but I know I instantly respawn in the exact same spot with no difference of my character other than my items flying out upon using `/kill` as a vampire.

**Comment by williambl** [comment]
> I could make that into a separate issue if you would like, assumingly being a bug. I haven't tested it with jumping into the void, but I know I instantly respawn in the exact same spot with no difference of my character other than my items flying out upon using `/kill` as a vampire.

Thanks. I can't seem to reproduce it myself, so that'd be useful.

**Comment by williambl** [comment]
Should be working in 1.5.3.

**Comment by Virusnest** [comment]
can this be togglable because I would like to have hybrids I'm my smp

**Comment by williambl** [comment]
> can this be togglable because I would like to have hybrids I'm my smp

To become a hybrid, start as one origin, then later convert to vampire with the vampire blood injector.
