### ISSUE TITLE
(Bug) Brightness issue

### ISSUE THREAD

**Issue by Virusnest** [williambl/haema#35]
if you chose to be the merling and go underwater it is very bright and the hammer is very high even on moody brightness

**Comment by Virusnest** [comment]
Idea:
Gamma cape for either underwater or global

**Comment by williambl** [comment]
Thanks for reporting. I'll look into it. You can turn the brightness effect down for now in the mod settings.

**Comment by Virusnest** [comment]
ok thx for letting me know

**Comment by williambl** [comment]
Is this still an issue in 1.6?

**Comment by williambl** [comment]
Closing due to lack of information.
