### ISSUE TITLE
Velocity/Bungeecord connection fails

### ISSUE THREAD

**Issue by TMShader** [williambl/haema#46]
When joining thru a velocity proxy the server goes into a join loop and than crashes.

Here is the error that is repeated over and over again:
![image](https://user-images.githubusercontent.com/43723765/112020752-e87b0700-8b30-11eb-88b2-85ac28c6f0f4.png)

And here are the mods on the server:
![image](https://user-images.githubusercontent.com/43723765/112020994-211ae080-8b31-11eb-9d56-434fea4d116c.png)

**Comment by williambl** [comment]
Just to be completely sure, does it work without Haema?

**Comment by TMShader** [comment]
I didn't try it yet, but the only error comes from haema. It doesn't give the error if it's not behind a proxy

I'll try it without haema and get back to you, but in 90% sure that haema is the porblem :(

**Comment by TMShader** [comment]
I looked into it and it seems like the proxy can't encode a packed and haema is not the problem. Pehkui is the actual problem. I'll close this now.
