### ISSUE TITLE
Crash while starting Launcher

### ISSUE THREAD

**Issue by Toma400** [williambl/haema#65]
[crash-2021-06-14_22.29.52-client.txt](https://github.com/williambl/haema/files/6651111/crash-2021-06-14_22.29.52-client.txt)

As in title - launcher crashes after showing me critical warn with Haema.

**Comment by williambl** [comment]
The mod 'bosses of mass destruction' is crashing because it needs GeckoLib but it's not installed, nothing to do with Haema.

**Comment by Toma400** [comment]
Please update dependencies then, there was no info on both file dependencies (https://www.curseforge.com/minecraft/mc-mods/haema/files/3343576) nor site (https://www.curseforge.com/minecraft/mc-mods/haema).

**Comment by Toma400** [comment]
This time it is related to Haema, as removing Haema removed the crash issue. I installed GeckoLib, so it is no longer BOMD
[crash-2021-06-15_21.04.26-client.txt](https://github.com/williambl/haema/files/6658073/crash-2021-06-15_21.04.26-client.txt)
