### ISSUE TITLE
Incompatibility with Origins - crashes on startup in 1.17

### ISSUE THREAD

**Issue by Keltas** [williambl/haema#66]
When launching with both of the mods installed, the game crashes with the logs attached below. I can load the game with either of the mods enabled but not both. The crash occurs only on 1.17. Minecraft 1.16.5 launches fine.
Mod List:
"haema-1.7.0-1.17"
"Origins-1.17-1.0.0"
"fabric-language-kotlin-1.6.1+kotlin.1.5.10"
"fabric-api-0.35.2+1.17"

[crash-2021-06-20_13.11.42-client.txt](https://github.com/williambl/haema/files/6682242/crash-2021-06-20_13.11.42-client.txt)
[latest.log](https://github.com/williambl/haema/files/6682245/latest.log)

**Comment by williambl** [comment]
Fixed.
