### ISSUE TITLE
Keep getting text "errors with currently selected data packs prevented world from loading"

### ISSUE THREAD

**Issue by beautiful-lunatic** [williambl/haema#68]
Keep getting this message even though I don't have or use datapacks.

**Comment by MoZarka** [comment]
yep, same. exclusively this mods problem

**Comment by williambl** [comment]
Please give a log.

**Comment by williambl** [comment]
I've been informed this only happens with Adorn installed, can this be confirmed?

**Comment by beautiful-lunatic** [comment]
> I've been informed this only happens with Adorn installed, can this be confirmed?

Sorry I never got back to you earlier, I believe it was Adorn since I have that installed. I did get it to run, but for some reason the Vampire Hunter Pillagers were a little bugged. Their bodies weren't fully rendered or loaded, so they were just floating heads and arms that didn't make any noise

**Comment by williambl** [comment]
Actually this seems to be an issue with LibCD.

**Comment by williambl** [comment]
> Vampire Hunter Pillagers were a little bugged

Known issue, will be fixed.

**Comment by williambl** [comment]
Should to be fixed in 1.7.2?
