### ISSUE TITLE
Loop at loading screen

### ISSUE THREAD

**Issue by Toma400** [williambl/haema#69]
[not-crash-report.txt](https://github.com/williambl/haema/files/6715131/not-crash-report.txt)

As stated on CurseForge page, game loops at loading screen forever, spamming console and not allowing to do anything. It is not precisely crash, as it goes on and on, until you hit Windows key and turn Minecraft off manually.
I hope my log extraction from fatal part of it is correct.

**Comment by williambl** [comment]
Does it still happen if you update architectury?

**Comment by Toma400** [comment]
Yeah, it was architectury problem indeed. Sorry for the problem ^^
