### ISSUE TITLE
Vision Bug

### ISSUE THREAD

**Issue by FanbiAkyso** [williambl/haema#73]
Vision is bugged, doesn't have any edits to the saturation/desaturation or brightness

**Comment by williambl** [comment]
Cannot reproduce, can you reproduce with only Haema + required dependencies installed?

**Comment by FanbiAkyso** [comment]
hello, yes, i can, its a visual only bug. i am on version 1.17. 

![2021-07-20_08 00 01](https://user-images.githubusercontent.com/70580550/126253041-cdc37e25-7db3-4f52-8327-83ceb2ea8eb9.png)
![2021-07-20_07 58 49](https://user-images.githubusercontent.com/70580550/126253056-845b554b-f4f1-4e2f-95a5-3be18b42a734.png)
![2021-07-20_07 59 58](https://user-images.githubusercontent.com/70580550/126253061-25b5ac37-e2ca-49f7-a648-148030bcffd3.png)

theres none of the desaturation there usually is, no night vision, and no weird colouring.

**Comment by verbina29** [comment]
I've been getting this too. I hope it gets fixed soon, I really liked the filter!

**Comment by williambl** [comment]
Should be fixed in 1.7.5.
