### ISSUE TITLE
Vampires crash when feeding while Flan is installed

### ISSUE THREAD

**Issue by TritonJ73** [williambl/haema#76]
My players are not in a claim, yet any time they try to feed as Vampires, they crash, I tested it myself, and am attaching the crash report.
[crash-2021-07-18_10.58.07-client.txt](https://github.com/williambl/haema/files/6836485/crash-2021-07-18_10.58.07-client.txt)

**Comment by williambl** [comment]
Try 1.7.1.

**Comment by TritonJ73** [comment]
yeah, 1.71. seems to work! thanks!
