### ISSUE TITLE
Giving a non vampire Sunlight Sickness with the effect command crashes the game. 

### ISSUE THREAD

**Issue by FanbiAkyso** [williambl/haema#77]
Crash Report here, other mods are inconsequential. 
	
	To recreate give the sunlight sickness effect to a normal human. 
	
[crash-2021-07-20_10.05.42-server.txt](https://github.com/williambl/haema/files/6845552/crash-2021-07-20_10.05.42-server.txt)

**Comment by Dual-Iron** [comment]
Can confirm. Additionally, the effect is saved, causing the game to crash upon entering the world.
```The game crashed whilst ticking player
Error: java.lang.ClassCastException: class net.minecraft.class_1702 cannot be cast to class com.williambl.haema.VampireBloodManager (net.minecraft.class_1702 and com.williambl.haema.VampireBloodManager are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @141e5bef)```

**Comment by williambl** [comment]
Thanks for the report.
