### ISSUE TITLE
Haema + Bewitchment Compatibility Crash on 1.17.1

### ISSUE THREAD

**Issue by ArcusMG** [williambl/haema#84]
My game crashes if both Haema and Bewitchment (plus all of Bewitchment's dependancies) are installed. Separately they work fine but when installed together I get a crash that seems to be related to the compatibility in Haema. Pastebin below is my crash log. 

Installed mods:
somnus-fabric-0.0.12-1.17.jar
bewitchment-1.17-2.jar
Cardinal-Components-API-3.1.1.jar
cloth-config-5.0.38-fabric.jar
fabric-api-0.37.2+1.17.jar
fabric-language-kotlin-1.6.3+kotlin.1.5.21.jar
haema-1.7.4+1.17.jar
impersonate-2.3.3.jar
pal-1.3.0.jar
Patchouli-1.17-54-FABRIC.jar
Pehkui-2.3.0+1.14.4-1.17.1.jar
trinkets-3.0.2.jar

https://pastebin.com/zUKMyBRF

**Comment by williambl** [comment]
Should be fixed in 1.7.5.
