### ISSUE TITLE
Haema is preventing my game from starting

### ISSUE THREAD

**Issue by RebelGearBoy** [williambl/haema#88]
ok So I plan to start a Hardcore world with the mod haema and when I start the game it crashes right after that. When I remove it from mods folder and have the other mods installed, The game launches like normal. So my question is. Is there any mods The mod is incompatible with? Please get to me when someone can. I plan to start a series with this And need to get at it. Please and Thank You!

**Comment by williambl** [comment]
Please give a log, found in [your minecraft folder] -> logs -> latest.log

**Comment by crys-heart** [comment]
I've been having a similar issue. Here are the logs.
[latest.log](https://github.com/williambl/haema/files/7126036/latest.log)
[crash-2021-09-08_13.14.53-client.txt](https://github.com/williambl/haema/files/7126039/crash-2021-09-08_13.14.53-client.txt)

Here are some earlier logs where I loaded only Haema. Don't know if it'll help but I reckon I'd add them anyways.
[2021-09-08-2.log](https://github.com/williambl/haema/files/7126074/2021-09-08-2.log)
[crash-2021-09-08_12.57.31-client.txt](https://github.com/williambl/haema/files/7126048/crash-2021-09-08_12.57.31-client.txt)

**Comment by williambl** [comment]
@crys-heart 

This is an issue with cloth config, please delete your haema config file
