### ISSUE TITLE
Haema prevents server from starting.

### ISSUE THREAD

**Issue by toErIpNid** [williambl/haema#90]
When haema is installed in my modpack for my server, it causes an error making the server unable to start. I think. All I know is that when I take it out the server works again. 
[latest.txt](https://github.com/williambl/haema/files/7087092/latest.txt)

**Comment by williambl** [comment]
You seem to have linked the log without Haema.

**Comment by williambl** [comment]
Any update?

**Comment by williambl** [comment]
Closing due to a lack of further information.
