### ISSUE TITLE
minecraft crashes if using the ritual table

### ISSUE THREAD

**Issue by KlaraChaos** [williambl/haema#98]
[crash-2021-11-18_23.46.15-client.txt](https://github.com/williambl/haema/files/7566560/crash-2021-11-18_23.46.15-client.txt)

idk if i did anything wrong but i decided to report this in just in case

**Comment by easfaff** [comment]
I have the same problem as well so i think its a bug not something you did wrong

**Comment by williambl** [comment]
Closed by c26198474ff211d9132a7c1bf539160101454e90
